[2024-07-16T08:54:08.116+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:08.128+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-16T08:54:08.139+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:08.142+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-16T08:54:08.158+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:54:08.159+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-16T08:54:08.164+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:54:08.164+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-16T08:54:08.165+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:54:08.165+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]>
[2024-07-16T08:54:08.165+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-16T08:54:08.165+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:54:08.171+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:54:08.171+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:54:08.176+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-16T08:54:08.176+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [queued]>
[2024-07-16T08:54:08.176+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-16T08:54:08.190+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): read_from_mysql> on 2023-01-27 00:00:00+00:00
[2024-07-16T08:54:08.200+0000] {standard_task_runner.py:60} INFO - Started process 274 to run task
[2024-07-16T08:54:08.203+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sample_dag', 'read_from_mysql', 'scheduled__2023-01-27T00:00:00+00:00', '--job-id', '1291', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmp74tuj1kw']
[2024-07-16T08:54:08.205+0000] {standard_task_runner.py:88} INFO - Job 1291: Subtask read_from_mysql
[2024-07-16T08:54:08.206+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x710a46078ca0>]
[2024-07-16T08:54:08.249+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:08.252+0000] {task_command.py:423} INFO - Running <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-27T00:00:00+00:00 [running]> on host 6dec4fd91ad6
[2024-07-16T08:54:08.252+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 274)
[2024-07-16T08:54:08.253+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 274)
[2024-07-16T08:54:08.253+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-16T08:54:08.293+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:08.295+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-16T08:54:08.299+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-16T08:54:08.327+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-16T08:54:08.345+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_dag' AIRFLOW_CTX_TASK_ID='read_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-27T00:00:00+00:00'
[2024-07-16T08:54:08.345+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-16T08:54:08.346+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-16T08:54:08.356+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-16T08:54:13.244+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:18.283+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:23.322+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:28.362+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:33.408+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:38.473+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:41.961+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 8, in read_from_mysql
    connection = mysql_hook.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mysql_container' (-3)")
[2024-07-16T08:54:41.967+0000] {taskinstance.py:527} DEBUG - Task Duration set to 33.802327
[2024-07-16T08:54:41.969+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-16T08:54:41.969+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_dag, task_id=read_from_mysql, execution_date=20230127T000000, start_date=20240716T085408, end_date=20240716T085441
[2024-07-16T08:54:41.983+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-16T08:54:41.984+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1291 for task read_from_mysql ((2005, "Unknown server host 'mysql_container' (-3)"); 274)
[2024-07-16T08:54:42.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T08:54:42.032+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun sample_dag @ 2023-01-27 00:00:00+00:00: scheduled__2023-01-27T00:00:00+00:00, state:running, queued_at: 2024-07-16 08:54:06.330366+00:00. externally triggered: False>: 0 task(s)
[2024-07-16T08:54:42.032+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
