[2024-07-17T09:28:23.966+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:28:23.979+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:28:23.996+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:28:23.999+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:28:24.029+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:28:24.029+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:28:24.029+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:28:24.036+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:28:24.036+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]>
[2024-07-17T09:28:24.036+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:28:24.041+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:28:24.044+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:28:24.049+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:28:24.049+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [queued]>
[2024-07-17T09:28:24.049+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T09:28:24.065+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2023-03-29 00:00:00+00:00
[2024-07-17T09:28:24.075+0000] {standard_task_runner.py:60} INFO - Started process 1126 to run task
[2024-07-17T09:28:24.078+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'scheduled__2023-03-29T00:00:00+00:00', '--job-id', '1760', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpa5ux4kjc']
[2024-07-17T09:28:24.080+0000] {standard_task_runner.py:88} INFO - Job 1760: Subtask extract_from_mysql
[2024-07-17T09:28:24.082+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x799cf7552f80>]
[2024-07-17T09:28:24.139+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:28:24.144+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-03-29T00:00:00+00:00 [running]> on host a88c97f6715f
[2024-07-17T09:28:24.144+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 1126)
[2024-07-17T09:28:24.145+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 1126)
[2024-07-17T09:28:24.145+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:28:24.195+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:28:24.198+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:28:24.205+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:28:24.238+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:28:24.253+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-29T00:00:00+00:00'
[2024-07-17T09:28:24.254+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:28:24.254+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:28:24.265+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T09:28:24.279+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2024-07-17T09:28:24.288+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-17T09:28:24.289+0000] {__init__.py:73} DEBUG - Lineage called with inlets: [], outlets: []
[2024-07-17T09:28:24.299+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:28:24.299+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20230329T000000, start_date=20240717T092824, end_date=20240717T092824
[2024-07-17T09:28:24.300+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.262899
[2024-07-17T09:28:24.312+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:28:24.333+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-17T09:28:24.599+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-03-29 00:00:00+00:00: scheduled__2023-03-29T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:28:22.015450+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T09:28:24.599+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-03-29 00:00:00+00:00: scheduled__2023-03-29T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:28:22.015450+00:00. externally triggered: False>: 2 task(s)
[2024-07-17T09:28:24.599+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-03-29T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:28:24.600+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-03-29T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:28:24.601+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-03-29T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:28:24.601+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-03-29T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:28:24.601+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-03-29T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:28:24.602+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-03-29T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:28:24.602+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-03-29T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:28:24.602+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-03-29T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:28:24.608+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
