[2024-07-17T14:54:22.764+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:54:22.776+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T14:54:22.792+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:54:22.796+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T14:54:22.825+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T14:54:22.825+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T14:54:22.826+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:54:22.826+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:54:22.826+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2024-07-17T14:54:22.830+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T14:54:22.832+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T14:54:22.835+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:54:22.835+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:54:22.835+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2024-07-17T14:54:22.835+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-17T14:54:22.849+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2023-07-21 00:00:00+00:00
[2024-07-17T14:54:22.857+0000] {standard_task_runner.py:60} INFO - Started process 429 to run task
[2024-07-17T14:54:22.861+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '2245', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmploudiycx']
[2024-07-17T14:54:22.862+0000] {standard_task_runner.py:88} INFO - Job 2245: Subtask extract_from_mysql
[2024-07-17T14:54:22.863+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x78a73b356f80>]
[2024-07-17T14:54:22.930+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:54:22.937+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-07-21T00:00:00+00:00 [running]> on host 8c50a8ad787d
[2024-07-17T14:54:22.937+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 429)
[2024-07-17T14:54:22.938+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 429)
[2024-07-17T14:54:22.938+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T14:54:22.993+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:54:22.996+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T14:54:23.002+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T14:54:23.038+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T14:54:23.054+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-21T00:00:00+00:00'
[2024-07-17T14:54:23.055+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T14:54:23.055+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T14:54:23.068+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T14:54:27.918+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:54:32.964+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:54:38.035+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:54:43.088+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:54:48.131+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:54:53.214+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:54:58.270+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:03.349+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:08.423+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:13.470+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:18.525+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:23.588+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:28.668+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:33.708+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:38.750+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:43.795+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:48.848+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:53.900+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:55:58.942+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:04.000+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:09.057+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:14.139+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:19.212+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:24.284+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:29.339+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:34.389+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:56:37.794+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 23, in extract_from_mysql
    extracted_df = mysql_hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 226, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '172.16.9.72' (115)")
[2024-07-17T14:56:37.803+0000] {taskinstance.py:527} DEBUG - Task Duration set to 134.97703
[2024-07-17T14:56:37.806+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T14:56:37.806+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20230721T000000, start_date=20240717T145422, end_date=20240717T145637
[2024-07-17T14:56:38.078+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T14:56:38.079+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2245 for task extract_from_mysql ((2002, "Can't connect to server on '172.16.9.72' (115)"); 429)
[2024-07-17T14:56:38.130+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T14:56:38.147+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-07-21 00:00:00+00:00: scheduled__2023-07-21T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:47:31.565123+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T14:56:38.147+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-07-21 00:00:00+00:00: scheduled__2023-07-21T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:47:31.565123+00:00. externally triggered: False>: 3 task(s)
[2024-07-17T14:56:38.148+0000] {taskinstance.py:1800} DEBUG - Setting task state for <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-21T00:00:00+00:00 [None]> to upstream_failed
[2024-07-17T14:56:38.148+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-21T00:00:00+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:56:38.148+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-21T00:00:00+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:56:38.148+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-21T00:00:00+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:56:38.148+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-07-21T00:00:00+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:56:38.149+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-21T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:56:38.149+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-21T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:56:38.149+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-21T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:56:38.149+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-07-21T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:56:38.150+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-07-21T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:56:38.150+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-07-21T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:56:38.150+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-07-21T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:56:38.150+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-07-21T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:56:38.156+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
