[2024-07-17T14:19:40.869+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:19:40.878+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T14:19:40.887+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:19:40.889+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T14:19:40.905+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T14:19:40.905+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:19:40.911+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:19:40.911+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T14:19:40.912+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]>
[2024-07-17T14:19:40.912+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:19:40.914+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:19:40.919+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T14:19:40.919+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T14:19:40.919+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [queued]>
[2024-07-17T14:19:40.920+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-17T14:19:40.931+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2023-06-02 00:00:00+00:00
[2024-07-17T14:19:40.937+0000] {standard_task_runner.py:60} INFO - Started process 212 to run task
[2024-07-17T14:19:40.939+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'extract_from_mysql', 'scheduled__2023-06-02T00:00:00+00:00', '--job-id', '2134', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmplob_bvc8']
[2024-07-17T14:19:40.940+0000] {standard_task_runner.py:88} INFO - Job 2134: Subtask extract_from_mysql
[2024-07-17T14:19:40.941+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x763f8104af80>]
[2024-07-17T14:19:40.975+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:19:40.978+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-06-02T00:00:00+00:00 [running]> on host 8c50a8ad787d
[2024-07-17T14:19:40.978+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 212)
[2024-07-17T14:19:40.979+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 212)
[2024-07-17T14:19:40.979+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T14:19:41.006+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T14:19:41.008+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T14:19:41.011+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T14:19:41.030+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T14:19:41.041+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-06-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-02T00:00:00+00:00'
[2024-07-17T14:19:41.041+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T14:19:41.042+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T14:19:41.049+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-17T14:19:45.988+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:19:51.032+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:19:56.074+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:01.115+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:06.159+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:11.205+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:16.254+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:21.294+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:26.342+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:31.425+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:36.476+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:41.526+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:46.565+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:51.646+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:20:56.693+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:01.761+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:06.814+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:11.894+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:16.935+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:22.004+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:27.056+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:32.101+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:37.141+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:42.190+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:47.239+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:52.277+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-17T14:21:55.758+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 20, in extract_from_mysql
    df = mysql_hook.get_pandas_df(sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 226, in get_pandas_df
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '172.16.9.72' (115)")
[2024-07-17T14:21:55.788+0000] {taskinstance.py:527} DEBUG - Task Duration set to 134.875919
[2024-07-17T14:21:55.792+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T14:21:55.794+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=hive_etl, task_id=extract_from_mysql, execution_date=20230602T000000, start_date=20240717T141940, end_date=20240717T142155
[2024-07-17T14:21:55.822+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T14:21:55.822+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2134 for task extract_from_mysql ((2002, "Can't connect to server on '172.16.9.72' (115)"); 212)
[2024-07-17T14:21:55.861+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T14:21:55.872+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-06-02 00:00:00+00:00: scheduled__2023-06-02T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:08:48.407469+00:00. externally triggered: False>: 4 task(s)
[2024-07-17T14:21:55.873+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-06-02 00:00:00+00:00: scheduled__2023-06-02T00:00:00+00:00, state:running, queued_at: 2024-07-17 14:08:48.407469+00:00. externally triggered: False>: 3 task(s)
[2024-07-17T14:21:55.873+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:21:55.873+0000] {taskinstance.py:1800} DEBUG - Setting task state for <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-02T00:00:00+00:00 [None]> to upstream_failed
[2024-07-17T14:21:55.874+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-02T00:00:00+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:21:55.874+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-02T00:00:00+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'extract_from_mysql'}
[2024-07-17T14:21:55.874+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-06-02T00:00:00+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:21:55.874+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:21:55.874+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:21:55.874+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-02T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T14:21:55.875+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:21:55.875+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T14:21:55.875+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:21:55.875+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-06-02T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T14:21:55.875+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-06-02T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T14:21:55.879+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
