[2024-07-17T09:29:31.671+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:29:31.685+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:29:31.693+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:29:31.695+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:29:31.709+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:29:31.709+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:29:31.709+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:29:31.713+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:29:31.714+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]>
[2024-07-17T09:29:31.714+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:29:31.717+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:29:31.718+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:29:31.719+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:29:31.720+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [queued]>
[2024-07-17T09:29:31.720+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T09:29:31.729+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): create_hive_table> on 2023-04-07 00:00:00+00:00
[2024-07-17T09:29:31.733+0000] {standard_task_runner.py:60} INFO - Started process 1204 to run task
[2024-07-17T09:29:31.735+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'create_hive_table', 'scheduled__2023-04-07T00:00:00+00:00', '--job-id', '1783', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpxp2ea3w6']
[2024-07-17T09:29:31.736+0000] {standard_task_runner.py:88} INFO - Job 1783: Subtask create_hive_table
[2024-07-17T09:29:31.737+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x799cf7552f80>]
[2024-07-17T09:29:31.770+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:29:31.773+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [running]> on host a88c97f6715f
[2024-07-17T09:29:31.773+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 1204)
[2024-07-17T09:29:31.773+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 1204)
[2024-07-17T09:29:31.773+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:29:31.800+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:29:31.802+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:29:31.805+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:29:31.822+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:29:31.831+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='create_hive_table' AIRFLOW_CTX_EXECUTION_DATE='2023-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-07T00:00:00+00:00'
[2024-07-17T09:29:31.831+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:29:31.832+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:29:31.833+0000] {TSocket.py:145} INFO - Could not connect to ('172.16.9.72', 10000)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 140, in open
    handle.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-07-17T09:29:31.834+0000] {TSocket.py:148} ERROR - Could not connect to any of [('172.16.9.72', 10000)]
[2024-07-17T09:29:31.834+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 23, in create_hive_table
    conn = hive.Connection(host='172.16.9.72', port=10000, username='hive')
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 269, in __init__
    self._transport.open()
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift_sasl/__init__.py", line 74, in open
    self._trans.open()
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 149, in open
    raise TTransportException(type=TTransportException.NOT_OPEN, message=msg)
thrift.transport.TTransport.TTransportException: Could not connect to any of [('172.16.9.72', 10000)]
[2024-07-17T09:29:31.839+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.125601
[2024-07-17T09:29:31.840+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:29:31.840+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=hive_etl, task_id=create_hive_table, execution_date=20230407T000000, start_date=20240717T092931, end_date=20240717T092931
[2024-07-17T09:29:31.848+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:29:31.848+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1783 for task create_hive_table (Could not connect to any of [('172.16.9.72', 10000)]; 1204)
[2024-07-17T09:29:31.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T09:29:31.955+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-04-07 00:00:00+00:00: scheduled__2023-04-07T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:29:28.338016+00:00. externally triggered: False>: 3 task(s)
[2024-07-17T09:29:31.956+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-04-07 00:00:00+00:00: scheduled__2023-04-07T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:29:28.338016+00:00. externally triggered: False>: 3 task(s)
[2024-07-17T09:29:31.957+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-07T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:29:31.958+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-07T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:29:31.958+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-07T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_hive_table'}
[2024-07-17T09:29:31.959+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-07T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:29:31.959+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-07T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:29:31.959+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-07T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:29:31.960+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-04-07T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:29:31.960+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-07T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:29:31.960+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T09:29:31.960825+00:00 and task will be retried at 2024-07-17T09:34:31.839809+00:00.
[2024-07-17T09:29:31.961+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T09:29:31.960825+00:00 and task will be retried at 2024-07-17T09:34:31.839809+00:00.
[2024-07-17T09:29:31.961+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T09:29:31.961+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.create_hive_table scheduled__2023-04-07T00:00:00+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:29:31.968+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
