[2024-07-17T09:44:30.546+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:30.566+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:44:30.587+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:30.591+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:44:30.625+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:44:30.636+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:30.637+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:44:30.637+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:30.638+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2024-07-17T09:44:30.645+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:30.652+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:44:30.652+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:44:30.653+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:30.653+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [queued]>
[2024-07-17T09:44:30.653+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T09:44:30.673+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_data_into_hive> on 2023-04-17 00:00:00+00:00
[2024-07-17T09:44:30.692+0000] {standard_task_runner.py:60} INFO - Started process 219 to run task
[2024-07-17T09:44:30.700+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'load_data_into_hive', 'scheduled__2023-04-17T00:00:00+00:00', '--job-id', '1864', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmppu9vs65h']
[2024-07-17T09:44:30.702+0000] {standard_task_runner.py:88} INFO - Job 1864: Subtask load_data_into_hive
[2024-07-17T09:44:30.703+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7a4457f56f80>]
[2024-07-17T09:44:30.804+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:30.808+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [running]> on host d0d849f06491
[2024-07-17T09:44:30.809+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 219)
[2024-07-17T09:44:30.809+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 219)
[2024-07-17T09:44:30.810+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:44:30.886+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:44:30.889+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:44:30.901+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:44:30.945+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:44:30.958+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='load_data_into_hive' AIRFLOW_CTX_EXECUTION_DATE='2023-04-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-17T00:00:00+00:00'
[2024-07-17T09:44:30.959+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:44:30.960+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:44:31.152+0000] {hive.py:609} DEBUG - TOpenSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), serverProtocolVersion=5, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'e\x06\xba\x82#mJ\x04\xbe\xa9\x8e\xcd\xf1s#+', secret=b'S\xc5\x93l0\x83D.\xab)\x1er*\xc7b\xb8')), configuration={'hive.server2.thrift.resultset.default.fetch.size': '1000'})
[2024-07-17T09:44:31.152+0000] {hive.py:475} INFO - USE `default`
[2024-07-17T09:44:31.152+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'e\x06\xba\x82#mJ\x04\xbe\xa9\x8e\xcd\xf1s#+', secret=b'S\xc5\x93l0\x83D.\xab)\x1er*\xc7b\xb8')), statement='USE `default`', confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T09:44:31.383+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), operationHandle=TOperationHandle(operationId=THandleIdentifier(guid=b'\xf5R\x04\xb0C\xdcA\xdd\x86\x17\x1e\xa1\xad\xcf9E', secret=b'\xea\xe2\xa8]<X@X\x87\xdf\x8b\xbe\xaa\x1c\xfd\xdc'), operationType=0, hasResultSet=False, modifiedRowCount=None))
[2024-07-17T09:44:31.384+0000] {hive.py:609} DEBUG - TCloseOperationResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None))
[2024-07-17T09:44:31.385+0000] {hive.py:475} INFO - LOAD DATA LOCAL INPATH '/tmp/test_table.csv' INTO TABLE my_table
[2024-07-17T09:44:31.385+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'e\x06\xba\x82#mJ\x04\xbe\xa9\x8e\xcd\xf1s#+', secret=b'S\xc5\x93l0\x83D.\xab)\x1er*\xc7b\xb8')), statement="LOAD DATA LOCAL INPATH '/tmp/test_table.csv' INTO TABLE my_table", confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T09:44:31.547+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv"), operationHandle=None)
[2024-07-17T09:44:31.548+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 39, in load_data_into_hive
    cursor.execute("LOAD DATA LOCAL INPATH '/tmp/test_table.csv' INTO TABLE my_table")
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv"), operationHandle=None)
[2024-07-17T09:44:31.559+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.921285
[2024-07-17T09:44:31.562+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:44:31.562+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=hive_etl, task_id=load_data_into_hive, execution_date=20230417T000000, start_date=20240717T094430, end_date=20240717T094431
[2024-07-17T09:44:31.581+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:44:31.582+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1864 for task load_data_into_hive (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv"), operationHandle=None); 219)
[2024-07-17T09:44:31.611+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T09:44:31.633+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-04-17 00:00:00+00:00: scheduled__2023-04-17T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:44:18.229289+00:00. externally triggered: False>: 2 task(s)
[2024-07-17T09:44:31.634+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-04-17 00:00:00+00:00: scheduled__2023-04-17T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:44:18.229289+00:00. externally triggered: False>: 2 task(s)
[2024-07-17T09:44:31.634+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-17T09:44:31.634+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:31.635+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T09:44:31.635069+00:00 and task will be retried at 2024-07-17T09:49:31.559828+00:00.
[2024-07-17T09:44:31.635+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-17T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-07-17T09:44:31.635069+00:00 and task will be retried at 2024-07-17T09:49:31.559828+00:00.
[2024-07-17T09:44:31.636+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-17T00:00:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:44:31.636+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-04-17T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:44:31.636+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-17T00:00:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:44:31.637+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-17T00:00:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:44:31.644+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
