[2024-07-16T09:19:45.248+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T09:19:45.261+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-16T09:19:45.269+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T09:19:45.271+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-16T09:19:45.287+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T09:19:45.288+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-16T09:19:45.288+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T09:19:45.288+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-16T09:19:45.288+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T09:19:45.288+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]>
[2024-07-16T09:19:45.290+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T09:19:45.292+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-16T09:19:45.292+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T09:19:45.295+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-16T09:19:45.295+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T09:19:45.295+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [queued]>
[2024-07-16T09:19:45.295+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-07-16T09:19:45.304+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): read_from_mysql> on 2024-07-16 09:14:58.923376+00:00
[2024-07-16T09:19:45.310+0000] {standard_task_runner.py:60} INFO - Started process 277 to run task
[2024-07-16T09:19:45.312+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sample_dag', 'read_from_mysql', 'manual__2024-07-16T09:14:58.923376+00:00', '--job-id', '1353', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmp_kb0r51p']
[2024-07-16T09:19:45.314+0000] {standard_task_runner.py:88} INFO - Job 1353: Subtask read_from_mysql
[2024-07-16T09:19:45.314+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x746f87084ca0>]
[2024-07-16T09:19:45.344+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T09:19:45.346+0000] {task_command.py:423} INFO - Running <TaskInstance: sample_dag.read_from_mysql manual__2024-07-16T09:14:58.923376+00:00 [running]> on host fd06bd5975d6
[2024-07-16T09:19:45.346+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 277)
[2024-07-16T09:19:45.347+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 277)
[2024-07-16T09:19:45.347+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-16T09:19:45.378+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T09:19:45.380+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-16T09:19:45.382+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-16T09:19:45.398+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-16T09:19:45.406+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_dag' AIRFLOW_CTX_TASK_ID='read_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T09:14:58.923376+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T09:14:58.923376+00:00'
[2024-07-16T09:19:45.406+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-16T09:19:45.407+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-16T09:19:45.413+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-16T09:19:45.420+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 10, in read_from_mysql
    cursor.execute("SELECT * FROM test_table;")
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'mydatabase.test_table' doesn't exist")
[2024-07-16T09:19:45.426+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.137398
[2024-07-16T09:19:45.427+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-16T09:19:45.427+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_dag, task_id=read_from_mysql, execution_date=20240716T091458, start_date=20240716T091945, end_date=20240716T091945
[2024-07-16T09:19:45.435+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-16T09:19:45.435+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1353 for task read_from_mysql ((1146, "Table 'mydatabase.test_table' doesn't exist"); 277)
[2024-07-16T09:19:45.444+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T09:19:45.454+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun sample_dag @ 2024-07-16 09:14:58.923376+00:00: manual__2024-07-16T09:14:58.923376+00:00, state:running, queued_at: 2024-07-16 09:19:43.272888+00:00. externally triggered: True>: 0 task(s)
[2024-07-16T09:19:45.455+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
