[2024-07-17T04:28:06.568+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:06.585+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T04:28:06.602+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:06.604+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T04:28:06.647+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T04:28:06.647+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:28:06.647+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:28:06.648+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T04:28:06.648+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]>
[2024-07-17T04:28:06.650+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:28:06.656+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T04:28:06.656+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:28:06.656+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T04:28:06.660+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [queued]>
[2024-07-17T04:28:06.661+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-17T04:28:06.677+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_into_hive> on 2024-07-17 04:28:02.397521+00:00
[2024-07-17T04:28:06.688+0000] {standard_task_runner.py:60} INFO - Started process 408 to run task
[2024-07-17T04:28:06.690+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_hive_with_connection', 'load_into_hive', 'manual__2024-07-17T04:28:02.397521+00:00', '--job-id', '1397', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmp00kegirk']
[2024-07-17T04:28:06.692+0000] {standard_task_runner.py:88} INFO - Job 1397: Subtask load_into_hive
[2024-07-17T04:28:06.692+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x70bb58c4af80>]
[2024-07-17T04:28:06.740+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:06.743+0000] {task_command.py:423} INFO - Running <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:28:02.397521+00:00 [running]> on host b2f9507f2158
[2024-07-17T04:28:06.743+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 408)
[2024-07-17T04:28:06.744+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 408)
[2024-07-17T04:28:06.744+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T04:28:06.772+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:28:06.774+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T04:28:06.778+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T04:28:06.802+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T04:28:06.812+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_hive_with_connection' AIRFLOW_CTX_TASK_ID='load_into_hive' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T04:28:02.397521+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T04:28:02.397521+00:00'
[2024-07-17T04:28:06.813+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T04:28:06.814+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T04:28:06.826+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 181, in write
    plus = self.handle.send(buff)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 48, in load_into_hive
    conn = hive.Connection(host='172.16.9.72', port=10000, username='hive')
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 269, in __init__
    self._transport.open()
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift_sasl/__init__.py", line 89, in open
    self._send_message(self.OK, initial_response)
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift_sasl/__init__.py", line 108, in _send_message
    self._trans.write(header + body)
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 188, in write
    raise TTransportException(message="unexpected exception", inner=e)
thrift.transport.TTransport.TTransportException: unexpected exception
[2024-07-17T04:28:06.847+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.198508
[2024-07-17T04:28:06.848+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T04:28:06.849+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_to_hive_with_connection, task_id=load_into_hive, execution_date=20240717T042802, start_date=20240717T042806, end_date=20240717T042806
[2024-07-17T04:28:06.862+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T04:28:06.862+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1397 for task load_into_hive (unexpected exception; 408)
[2024-07-17T04:28:06.902+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T04:28:06.915+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun mysql_to_hive_with_connection @ 2024-07-17 04:28:02.397521+00:00: manual__2024-07-17T04:28:02.397521+00:00, state:running, queued_at: 2024-07-17 04:28:02.403947+00:00. externally triggered: True>: 0 task(s)
[2024-07-17T04:28:06.915+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
