[2024-07-17T09:49:37.465+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:37.484+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T09:49:37.506+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:37.510+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T09:49:37.541+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T09:49:37.551+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:37.551+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T09:49:37.552+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:37.552+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-07-17T09:49:37.559+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:37.565+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T09:49:37.566+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T09:49:37.566+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:37.566+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-07-17T09:49:37.566+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-17T09:49:37.586+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_data_into_hive> on 2023-04-11 00:00:00+00:00
[2024-07-17T09:49:37.601+0000] {standard_task_runner.py:60} INFO - Started process 342 to run task
[2024-07-17T09:49:37.607+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'load_data_into_hive', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '1882', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpt19zuyp7']
[2024-07-17T09:49:37.610+0000] {standard_task_runner.py:88} INFO - Job 1882: Subtask load_data_into_hive
[2024-07-17T09:49:37.611+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7a4457f56f80>]
[2024-07-17T09:49:37.698+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:37.702+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-04-11T00:00:00+00:00 [running]> on host d0d849f06491
[2024-07-17T09:49:37.703+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 342)
[2024-07-17T09:49:37.703+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 342)
[2024-07-17T09:49:37.704+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T09:49:37.779+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T09:49:37.782+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T09:49:37.789+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T09:49:37.834+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T09:49:37.849+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='load_data_into_hive' AIRFLOW_CTX_EXECUTION_DATE='2023-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-11T00:00:00+00:00'
[2024-07-17T09:49:37.851+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T09:49:37.852+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T09:49:37.985+0000] {hive.py:609} DEBUG - TOpenSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), serverProtocolVersion=5, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x8d\xd6\xb1\xd5+\xa1L]\x86sn\xa4\xd2\xc5\xc2\xdf', secret=b'\x7f\xff\xc3\xe0\x1a~K\xdd\x92@\xe0=\x87\xda\xca\xb8')), configuration={'hive.server2.thrift.resultset.default.fetch.size': '1000'})
[2024-07-17T09:49:37.986+0000] {hive.py:475} INFO - USE `default`
[2024-07-17T09:49:37.987+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x8d\xd6\xb1\xd5+\xa1L]\x86sn\xa4\xd2\xc5\xc2\xdf', secret=b'\x7f\xff\xc3\xe0\x1a~K\xdd\x92@\xe0=\x87\xda\xca\xb8')), statement='USE `default`', confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T09:49:38.069+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), operationHandle=TOperationHandle(operationId=THandleIdentifier(guid=b'}?\x8d\xdfeCG\xa2\xb8\x8d0\xa36J\x00u', secret=b'\xc2\x9cf\xddd\xf4O#\xb8esNG}!M'), operationType=0, hasResultSet=False, modifiedRowCount=None))
[2024-07-17T09:49:38.070+0000] {hive.py:609} DEBUG - TCloseOperationResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None))
[2024-07-17T09:49:38.070+0000] {hive.py:475} INFO - LOAD DATA LOCAL INPATH '/tmp/test_table.csv' INTO TABLE my_table
[2024-07-17T09:49:38.071+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x8d\xd6\xb1\xd5+\xa1L]\x86sn\xa4\xd2\xc5\xc2\xdf', secret=b'\x7f\xff\xc3\xe0\x1a~K\xdd\x92@\xe0=\x87\xda\xca\xb8')), statement="LOAD DATA LOCAL INPATH '/tmp/test_table.csv' INTO TABLE my_table", confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T09:49:38.523+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv"), operationHandle=None)
[2024-07-17T09:49:38.523+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 39, in load_data_into_hive
    cursor.execute("LOAD DATA LOCAL INPATH '/tmp/test_table.csv' INTO TABLE my_table")
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv"), operationHandle=None)
[2024-07-17T09:49:38.533+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.980216
[2024-07-17T09:49:38.535+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T09:49:38.535+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=hive_etl, task_id=load_data_into_hive, execution_date=20230411T000000, start_date=20240717T094937, end_date=20240717T094938
[2024-07-17T09:49:38.659+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T09:49:38.659+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1882 for task load_data_into_hive (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:23 Invalid path ''/tmp/test_table.csv'': No files matching path file:/tmp/test_table.csv"), operationHandle=None); 342)
[2024-07-17T09:49:38.706+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T09:49:38.745+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-04-11 00:00:00+00:00: scheduled__2023-04-11T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:44:16.839422+00:00. externally triggered: False>: 2 task(s)
[2024-07-17T09:49:38.746+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-04-11 00:00:00+00:00: scheduled__2023-04-11T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:44:16.839422+00:00. externally triggered: False>: 1 task(s)
[2024-07-17T09:49:38.747+0000] {taskinstance.py:1800} DEBUG - Setting task state for <TaskInstance: hive_etl.end scheduled__2023-04-11T00:00:00+00:00 [None]> to upstream_failed
[2024-07-17T09:49:38.747+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-11T00:00:00+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:49:38.748+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-04-11T00:00:00+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T09:49:38.748+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-11T00:00:00+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T09:49:38.748+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-04-11T00:00:00+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T09:49:38.758+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
