[2024-07-17T10:20:23.934+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T10:20:23.969+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T10:20:23.999+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T10:20:24.007+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T10:20:24.045+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T10:20:24.045+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T10:20:24.046+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T10:20:24.055+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T10:20:24.056+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2024-07-17T10:20:24.059+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T10:20:24.065+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T10:20:24.065+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T10:20:24.068+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T10:20:24.069+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [queued]>
[2024-07-17T10:20:24.069+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-17T10:20:24.096+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_data_into_hive> on 2023-05-08 00:00:00+00:00
[2024-07-17T10:20:24.112+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2024-07-17T10:20:24.119+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hive_etl', 'load_data_into_hive', 'scheduled__2023-05-08T00:00:00+00:00', '--job-id', '2074', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpwodjc6w9']
[2024-07-17T10:20:24.120+0000] {standard_task_runner.py:88} INFO - Job 2074: Subtask load_data_into_hive
[2024-07-17T10:20:24.122+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7b3e5892af80>]
[2024-07-17T10:20:24.228+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T10:20:24.245+0000] {task_command.py:423} INFO - Running <TaskInstance: hive_etl.load_data_into_hive scheduled__2023-05-08T00:00:00+00:00 [running]> on host 5b4df633cab8
[2024-07-17T10:20:24.245+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 90)
[2024-07-17T10:20:24.246+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 90)
[2024-07-17T10:20:24.246+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T10:20:24.350+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T10:20:24.362+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T10:20:24.388+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T10:20:24.471+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T10:20:24.500+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hive_etl' AIRFLOW_CTX_TASK_ID='load_data_into_hive' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-08T00:00:00+00:00'
[2024-07-17T10:20:24.500+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T10:20:24.502+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T10:20:24.840+0000] {hive.py:609} DEBUG - TOpenSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), serverProtocolVersion=5, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x80\xf0\x14\xdcc\rOC\x80}h\xd9\xc84\xa2\xfb', secret=b'\x9b\xb42U\xc3\x82F\xc1\x9d\xc3\xa5\xf5\xdd\x9a\xef\x94')), configuration={'hive.server2.thrift.resultset.default.fetch.size': '1000'})
[2024-07-17T10:20:24.841+0000] {hive.py:475} INFO - USE `default`
[2024-07-17T10:20:24.841+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x80\xf0\x14\xdcc\rOC\x80}h\xd9\xc84\xa2\xfb', secret=b'\x9b\xb42U\xc3\x82F\xc1\x9d\xc3\xa5\xf5\xdd\x9a\xef\x94')), statement='USE `default`', confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T10:20:24.995+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None), operationHandle=TOperationHandle(operationId=THandleIdentifier(guid=b'-\xd6^f;\xcbCp\xbda\xc9\xb5\xa9*\x9a\xb8', secret=b'\xb66G\x0c\xd2{B\xe5\x9a\x93\x99\xe1\nD\xb0\xd0'), operationType=0, hasResultSet=False, modifiedRowCount=None))
[2024-07-17T10:20:24.996+0000] {hive.py:609} DEBUG - TCloseOperationResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None))
[2024-07-17T10:20:24.997+0000] {hive.py:475} INFO - LOAD DATA INPATH '/user/***/test_table.csv' INTO TABLE my_table
[2024-07-17T10:20:24.997+0000] {hive.py:479} DEBUG - TExecuteStatementReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=b'\x80\xf0\x14\xdcc\rOC\x80}h\xd9\xc84\xa2\xfb', secret=b'\x9b\xb42U\xc3\x82F\xc1\x9d\xc3\xa5\xf5\xdd\x9a\xef\x94')), statement="LOAD DATA INPATH '/user/airflow/test_table.csv' INTO TABLE my_table", confOverlay=None, runAsync=False, queryTimeout=0)
[2024-07-17T10:20:25.813+0000] {hive.py:609} DEBUG - TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv"), operationHandle=None)
[2024-07-17T10:20:25.814+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 44, in load_data_into_hive
    cursor.execute("LOAD DATA INPATH '/user/airflow/test_table.csv' INTO TABLE my_table")
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv"), operationHandle=None)
[2024-07-17T10:20:25.823+0000] {taskinstance.py:527} DEBUG - Task Duration set to 1.766938
[2024-07-17T10:20:25.826+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T10:20:25.827+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=hive_etl, task_id=load_data_into_hive, execution_date=20230508T000000, start_date=20240717T102024, end_date=20240717T102025
[2024-07-17T10:20:25.846+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T10:20:25.846+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2074 for task load_data_into_hive (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: SemanticException Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.SemanticException:Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv:22:6", 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:applyConstraintsAndGetFiles:LoadSemanticAnalyzer.java:151', 'org.apache.hadoop.hive.ql.parse.LoadSemanticAnalyzer:analyzeInternal:LoadSemanticAnalyzer.java:230', 'org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer:analyze:BaseSemanticAnalyzer.java:258', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:512', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: SemanticException Line 1:17 Invalid path ''/user/airflow/test_table.csv'': No files matching path hdfs://namenode:8020/user/airflow/test_table.csv"), operationHandle=None); 90)
[2024-07-17T10:20:25.870+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T10:20:25.902+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun hive_etl @ 2023-05-08 00:00:00+00:00: scheduled__2023-05-08T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:55:06.702642+00:00. externally triggered: False>: 2 task(s)
[2024-07-17T10:20:25.902+0000] {dagrun.py:897} DEBUG - number of scheduleable tasks for <DagRun hive_etl @ 2023-05-08 00:00:00+00:00: scheduled__2023-05-08T00:00:00+00:00, state:running, queued_at: 2024-07-17 09:55:06.702642+00:00. externally triggered: False>: 1 task(s)
[2024-07-17T10:20:25.903+0000] {taskinstance.py:1800} DEBUG - Setting task state for <TaskInstance: hive_etl.end scheduled__2023-05-08T00:00:00+00:00 [None]> to upstream_failed
[2024-07-17T10:20:25.904+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-05-08T00:00:00+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T10:20:25.904+0000] {taskinstance.py:1969} DEBUG - Dependencies not met for <TaskInstance: hive_etl.end scheduled__2023-05-08T00:00:00+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'load_data_into_hive'}
[2024-07-17T10:20:25.904+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-05-08T00:00:00+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T10:20:25.904+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: hive_etl.end scheduled__2023-05-08T00:00:00+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T10:20:25.915+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
