[2024-07-17T04:08:47.277+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:08:47.292+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-17T04:08:47.303+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:08:47.304+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-17T04:08:47.332+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-17T04:08:47.332+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:08:47.333+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:08:47.333+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-17T04:08:47.333+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]>
[2024-07-17T04:08:47.335+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-17T04:08:47.340+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-17T04:08:47.340+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-17T04:08:47.340+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-17T04:08:47.342+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [queued]>
[2024-07-17T04:08:47.342+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-07-17T04:08:47.356+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): load_into_hive> on 2024-07-17 04:03:39.854117+00:00
[2024-07-17T04:08:47.368+0000] {standard_task_runner.py:60} INFO - Started process 151 to run task
[2024-07-17T04:08:47.371+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_hive_with_connection', 'load_into_hive', 'manual__2024-07-17T04:03:39.854117+00:00', '--job-id', '1393', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmprio63goz']
[2024-07-17T04:08:47.373+0000] {standard_task_runner.py:88} INFO - Job 1393: Subtask load_into_hive
[2024-07-17T04:08:47.374+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x70bb58c4af80>]
[2024-07-17T04:08:47.417+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:08:47.420+0000] {task_command.py:423} INFO - Running <TaskInstance: mysql_to_hive_with_connection.load_into_hive manual__2024-07-17T04:03:39.854117+00:00 [running]> on host b2f9507f2158
[2024-07-17T04:08:47.420+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 151)
[2024-07-17T04:08:47.421+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 151)
[2024-07-17T04:08:47.421+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-17T04:08:47.454+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-17T04:08:47.456+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-17T04:08:47.460+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-17T04:08:47.481+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-17T04:08:47.491+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_hive_with_connection' AIRFLOW_CTX_TASK_ID='load_into_hive' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T04:03:39.854117+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T04:03:39.854117+00:00'
[2024-07-17T04:08:47.491+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-17T04:08:47.492+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-17T04:08:47.494+0000] {TSocket.py:145} INFO - Could not connect to ('172.16.9.72', 10000)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 140, in open
    handle.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-07-17T04:08:47.496+0000] {TSocket.py:148} ERROR - Could not connect to any of [('172.16.9.72', 10000)]
[2024-07-17T04:08:47.496+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 48, in load_into_hive
    conn = hive.Connection(host='172.16.9.72', port=10000, username='hive')
  File "/home/airflow/.local/lib/python3.10/site-packages/pyhive/hive.py", line 269, in __init__
    self._transport.open()
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift_sasl/__init__.py", line 74, in open
    self._trans.open()
  File "/home/airflow/.local/lib/python3.10/site-packages/thrift/transport/TSocket.py", line 149, in open
    raise TTransportException(type=TTransportException.NOT_OPEN, message=msg)
thrift.transport.TTransport.TTransportException: Could not connect to any of [('172.16.9.72', 10000)]
[2024-07-17T04:08:47.503+0000] {taskinstance.py:527} DEBUG - Task Duration set to 0.170011
[2024-07-17T04:08:47.504+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-17T04:08:47.504+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=mysql_to_hive_with_connection, task_id=load_into_hive, execution_date=20240717T040339, start_date=20240717T040847, end_date=20240717T040847
[2024-07-17T04:08:47.516+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-17T04:08:47.516+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1393 for task load_into_hive (Could not connect to any of [('172.16.9.72', 10000)]; 151)
[2024-07-17T04:08:47.543+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-17T04:08:47.564+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun mysql_to_hive_with_connection @ 2024-07-17 04:03:39.854117+00:00: manual__2024-07-17T04:03:39.854117+00:00, state:running, queued_at: 2024-07-17 04:03:39.868748+00:00. externally triggered: True>: 0 task(s)
[2024-07-17T04:08:47.564+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
