[2024-07-16T08:54:07.513+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:07.535+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-07-16T08:54:07.558+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:07.563+0000] {base_task_runner.py:72} DEBUG - Planning to run as the  user
[2024-07-16T08:54:07.596+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:54:07.596+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-07-16T08:54:07.607+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:54:07.607+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-07-16T08:54:07.608+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:54:07.608+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]>
[2024-07-16T08:54:07.608+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-07-16T08:54:07.609+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-07-16T08:54:07.616+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-07-16T08:54:07.617+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-07-16T08:54:07.624+0000] {taskinstance.py:1988} DEBUG - <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-07-16T08:54:07.625+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [queued]>
[2024-07-16T08:54:07.625+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-16T08:54:07.648+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): read_from_mysql> on 2023-01-25 00:00:00+00:00
[2024-07-16T08:54:07.661+0000] {standard_task_runner.py:60} INFO - Started process 269 to run task
[2024-07-16T08:54:07.665+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sample_dag', 'read_from_mysql', 'scheduled__2023-01-25T00:00:00+00:00', '--job-id', '1289', '--raw', '--subdir', 'DAGS_FOLDER/new.py', '--cfg-path', '/tmp/tmpaknlb7hs']
[2024-07-16T08:54:07.669+0000] {standard_task_runner.py:88} INFO - Job 1289: Subtask read_from_mysql
[2024-07-16T08:54:07.671+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x710a46078ca0>]
[2024-07-16T08:54:07.751+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:07.758+0000] {task_command.py:423} INFO - Running <TaskInstance: sample_dag.read_from_mysql scheduled__2023-01-25T00:00:00+00:00 [running]> on host 6dec4fd91ad6
[2024-07-16T08:54:07.759+0000] {settings.py:386} DEBUG - Disposing DB connection pool (PID 269)
[2024-07-16T08:54:07.759+0000] {settings.py:249} DEBUG - Setting up DB connection pool (PID 269)
[2024-07-16T08:54:07.760+0000] {settings.py:318} DEBUG - settings.prepare_engine_args(): Using NullPool
[2024-07-16T08:54:07.820+0000] {taskinstance.py:991} DEBUG - previous_execution_date was called
[2024-07-16T08:54:07.822+0000] {taskinstance.py:1769} DEBUG - Clearing XCom data
[2024-07-16T08:54:07.830+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-07-16T08:54:07.867+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-07-16T08:54:07.888+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_dag' AIRFLOW_CTX_TASK_ID='read_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-25T00:00:00+00:00'
[2024-07-16T08:54:07.889+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-07-16T08:54:07.890+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-07-16T08:54:07.904+0000] {base.py:83} INFO - Using connection ID 'mysql_default' for task execution.
[2024-07-16T08:54:12.720+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:17.788+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:22.828+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:27.868+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:32.908+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:37.949+0000] {job.py:209} DEBUG - [heartbeat]
[2024-07-16T08:54:41.529+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/new.py", line 8, in read_from_mysql
    connection = mysql_hook.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2005, "Unknown server host 'mysql_container' (-3)")
[2024-07-16T08:54:41.534+0000] {taskinstance.py:527} DEBUG - Task Duration set to 33.92527
[2024-07-16T08:54:41.534+0000] {taskinstance.py:549} DEBUG - Clearing next_method and next_kwargs.
[2024-07-16T08:54:41.535+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=sample_dag, task_id=read_from_mysql, execution_date=20230125T000000, start_date=20240716T085407, end_date=20240716T085441
[2024-07-16T08:54:41.543+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2024-07-16T08:54:41.543+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1289 for task read_from_mysql ((2005, "Unknown server host 'mysql_container' (-3)"); 269)
[2024-07-16T08:54:41.574+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T08:54:41.584+0000] {dagrun.py:876} DEBUG - number of tis tasks for <DagRun sample_dag @ 2023-01-25 00:00:00+00:00: scheduled__2023-01-25T00:00:00+00:00, state:running, queued_at: 2024-07-16 08:54:05.846520+00:00. externally triggered: False>: 0 task(s)
[2024-07-16T08:54:41.584+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
