[2024-07-17T14:57:37.272+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: hive_etl.extract_from_mysql scheduled__2023-08-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
